### PR TITLE
feat: add navigation menu

### PR DESCRIPTION
**Pull request by troggy**
- [x] menu

- [x] burger menu on narrow screens / mobile

- [x] show in burger on desktop until scrolled past the scene

### CODE REVIEW

**Comment by troggy** [comment]
Demo: https://habitat-landing-nxxlemfnp-troggy.vercel.app/

**Review by pinkiebell — APPROVED** [review]
Much Awesome

**Comment by pinkiebell** [comment]
@troggy We moved all our website stuff into https://github.com/0xHabitat/habitat/tree/master/web because we are starting to componentify all our elements. Do you want to open a new pull request over there for creditibility? Otherwise I'm picking the stuff into the other repo

**Comment by troggy** [comment]
@pinkiebell sure, will do. Somehow I saw the different code is in https://github.com/0xHabitat/habitat/tree/master/web

**Pull request merged**
